version: '3'

services:
  siep-mysql:
    image: mysql:5.7
    container_name: siep-mysql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "8106:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=siep
      - MYSQL_USER=siep
      - MYSQL_PASSWORD=siep
    networks:
      - back-tier

  siep-nginx:
    depends_on: 
      - siep-php-fpm
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: decyt/siep-nginx
    ports:
      - "8180:80"
    networks:
      - back-tier
      - front-tier

  siep-php-fpm:
    depends_on:
      - siep-mysql
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    image: decyt/siep-php-fpm
    container_name: siep-php-fpm
    links:
      - siep-mysql
    networks:
      - back-tier


volumes:
  mysql: {}

networks:
  front-tier:
    driver: overlay
  back-tier:
    driver: overlay
