apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: siep-nginx
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /siep
        backend:
          serviceName: siep-nginx
          servicePort: 80
